version: 0.2
# Environment variables must be set in the CodeBuild project settings
env:
  variables:
    AWS_REGION: us-east-1 # Change to your region
    ECR_REPO_NAME: my-app-repo
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      # Step 1: Echo status
      - echo "Logging in to Amazon ECR in region $AWS_REGION..."
      
      # Step 2: Use AWS STS to get the Account ID
      # NOTE: This is safer than relying on hardcoded variables
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      
      # Step 3: Define the full ECR URI using the Account ID and Region
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      # Step 4: The FIX - Retrieve password and pipe it to docker login without the external $()
      # (The $() is only needed if you want to capture the output, not just execute)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      
      # Now proceed to the build phase...
  build:
    commands:
      # 2. Build the Docker image
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      # 3. Push the Docker image to ECR
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG

# Optional: Output the Image URI for a downstream CodePipeline/CodeDeploy step
artifacts:
  files:
    - imagedefinitions.json # required for ECS deployment
  discard-paths: yes